### ISSUE TITLE
Slowdown issue may be a resource leak (either memory or CPU) - potentially getting caught in increasing loops/conditions.

### ISSUE THREAD

**Issue by AjdinoX** [darcymiranda/PFire#25] opened 2020-12-05 19:03 UTC

**Comment by oveldman** [comment] 2020-12-05 20:23
I did search for the problem, but I couldn't find a problem directly. Is there more information about this problem? 
Like when does it happen? Do I need to wait over time or does it happen when more users are logging in?

**Comment by AjdinoX** [comment] 2020-12-05 21:21
What this comment is referring to is the "high latency detected" message that starts appearing after an hour or several hours. It doesn't matter how many are on and talking. It even happens with 2 in the server only.

**Comment by TheLogster** [comment] 2020-12-05 21:27
This high latency message is not caused by the networking code, I have tested on my local network, with less than 5ms ping between clients. According to the docs, the open fire client sends a lot of "client information" chat messages to over come this.

**Comment by darcymiranda** [comment] 2020-12-06 23:13
I'm going to close this one in favour of keeping the other related issue open [here](https://github.com/darcymiranda/PFire/issues/19)

**Closed as completed by darcymiranda** 2020-12-06 23:13 UTC
